# Generated by Django 3.1.2 on 2020-10-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='style_picture',
            name='style_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gallery.painting'),
        ),
        migrations.AddField(
            model_name='uploaded_picture',
            name='upload_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gallery.painting'),
        ),
    ]
