# Generated by Django 3.1.2 on 2020-10-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0002_auto_20201028_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style_picture',
            name='style_pic',
        ),
        migrations.RemoveField(
            model_name='uploaded_picture',
            name='upload_pic',
        ),
        migrations.AddField(
            model_name='painting',
            name='style_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gallery.style_picture'),
        ),
        migrations.AddField(
            model_name='painting',
            name='upload_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gallery.uploaded_picture'),
        ),
    ]
