# Generated by Django 3.1.2 on 2020-11-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0003_auto_20201029_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='upload_style_combined',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
