# Generated by Django 3.1.2 on 2020-11-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0005_auto_20201109_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='painting',
            name='image_url',
        ),
    ]
