# Generated by Django 3.1.2 on 2020-11-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0006_remove_painting_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='Add_to_Gallery',
            field=models.BooleanField(default=True),
        ),
    ]
