# Generated by Django 3.1.2 on 2020-11-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0011_auto_20201111_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='upload_style_combined',
            field=models.URLField(blank=True, null=True),
        ),
    ]
