# Generated by Django 3.1.2 on 2020-11-15 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0012_auto_20201111_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='painting',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
