# Generated by Django 3.1.2 on 2020-11-15 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0013_auto_20201115_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
