# Generated by Django 3.1.2 on 2020-11-15 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0015_auto_20201115_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='painting',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='painting',
            name='style_pic',
            field=models.ImageField(null=True, upload_to='Gallery_images/Style_pic/'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='upload_pic',
            field=models.ImageField(null=True, upload_to='Gallery_images/Upload_pic/'),
        ),
    ]
