# Generated by Django 3.1.2 on 2020-11-15 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0017_auto_20201115_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
