# Generated by Django 3.1.2 on 2020-12-08 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gallery', '0018_auto_20201115_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='price',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
